Pulumi.prod.yaml
* fix tests ([commit](https://github.com/ayrorg/workspace-agent/commit/6df4a44c46d745603e6aa5807fdb26f9674eeeda))
=> chore: bump workspace-agent tag to `main-6df4a44`

Pulumi.prod.yaml
* feat: Do not throw on scheduled action ([commit](https://github.com/ayrorg/workspace-agent/commit/dc8cc060f30a9624de6e0bbe365e87c9189116a1))
=> chore: bump workspace-agent tag to `main-dc8cc06`

Pulumi.prod.yaml
* add Slack dev channel ([commit](https://github.com/ayrorg/workspace-agent/commit/9b8738c2cb931fd93c155844d3d7a2992d91330f))
=> chore: bump workspace-agent tag to `main-9b8738c`

Pulumi.prod.yaml
* feat: Add Firebase and refactor subscription ([commit](https://github.com/ayrorg/workspace-agent/commit/3eed94b9976c678a0331913cae43d455fcb6118e))
=> chore: bump workspace-agent tag to `main-3eed94b`

Pulumi.prod.yaml
* feat: Improve tracing (add TraceId and intstrumentation) ([commit](https://github.com/ayrorg/workspace-agent/commit/ee84780af09965dc7d9d181b55d57fb3b562cb95))
=> chore: bump workspace-agent tag to `main-ee84780`

Pulumi.prod.yaml
* Improve performance getting subscriptions form Google ([commit](https://github.com/ayrorg/workspace-agent/commit/0bb0ee99e7de4010265d485190767872d5e8857d))
* Add span to synchronizeSubscriptionByEvent ([commit](https://github.com/ayrorg/workspace-agent/commit/76d3e1b7de25b8cc402da161761b8c4ef21265cc))
=> chore: bump workspace-agent tag to `main-76d3e1b`

Pulumi.prod.yaml
* test: add maxResult to expect ([commit](https://github.com/ayrorg/workspace-agent/commit/56116fc648ec013016cb1d235a7a78c1a1beccdb))
* chore(deps-dev): bump @nestjs/testing from 8.0.6 to 8.1.2 ([commit](https://github.com/ayrorg/workspace-agent/commit/159def5b5d1e01f0fa29e016ce9a558aa323963b))
* chore(deps): bump @nestjs/core from 8.0.6 to 8.1.2 ([commit](https://github.com/ayrorg/workspace-agent/commit/72c41fb9263a0300cb97d8ab5920a5ab0a8095e7))
* chore(deps-dev): bump @types/node from 14.17.16 to 16.11.6 ([commit](https://github.com/ayrorg/workspace-agent/commit/1f35af22d9d03481d048456a5940038fd4438f23))
* chore(deps): bump fastify from 3.21.5 to 3.22.1 (indivorg/workspace-agent#30) ([commit](https://github.com/ayrorg/workspace-agent/commit/962b12164c4a8f30de75162 …
=> chore: bump workspace-agent tag to `main-0082f73`

Pulumi.prod.yaml
* Add @ayr-sales tag to warnings ([commit](https://github.com/ayrorg/workspace-agent/commit/0a86db0327d5c52e81a0bfe3781ce0b5ce2f3bd9))
=> chore: bump workspace-agent tag to `main-0a86db0`

Pulumi.prod.yaml
* add brackets on tag ([commit](https://github.com/ayrorg/workspace-agent/commit/569d4197c8f10402b238eef6dfac74ec6ca27111))
=> chore: bump workspace-agent tag to `main-569d419`

Pulumi.prod.yaml, resources/console/github/secrets.ts, resources/onboarding/google/slack-logger.ts, resources/onboarding/index.ts
- Add slack-logger and multiple repos for console
- add temporary user-api tag
=> small improvements

Pulumi.prod.yaml
* feat: Add debugging ([commit](https://github.com/ayrorg/tripletex-agent/commit/a40c332a3ad440fee47772a7ddb6b07a4e08f765))
=> chore: bump tripletex-agent tag to `main-a40c332`

Pulumi.prod.yaml
* feat: Add posthog (ayrorg/workspace-agent#79) ([commit](https://github.com/ayrorg/workspace-agent/commit/235c1ad556a1e4b86d2c0199f9c4e437135f849f))
=> chore: bump workspace-agent tag to `main-235c1ad`

Pulumi.prod.yaml
* add isGlobal to posthog ([commit](https://github.com/ayrorg/workspace-agent/commit/d95f5bce2bd9250687093c2c60c63fe78dd10a45))
=> chore: bump workspace-agent tag to `main-d95f5bc`

Pulumi.prod.yaml
* fix posthog issues ([commit](https://github.com/ayrorg/workspace-agent/commit/169a238588989979670740ed831c2e44f9b3805e))
* set Posthog flushAt and flushInterval to zero ([commit](https://github.com/ayrorg/workspace-agent/commit/84d7e9352ef0be383e716bd92cb81bbde5108a17))
=> chore: bump workspace-agent tag to `main-84d7e93`

Pulumi.prod.yaml
=> chore: bump freshworks-agent tag to `main-c50d19b`

Pulumi.prod.yaml
=> chore: bump freshworks-agent tag to `main-432525b`

Pulumi.prod.yaml
=> chore: bump freshworks-agent tag to `main-446a0e3`

Pulumi.prod.yaml
=> chore: bump freshworks-agent tag to `main-1b400bd`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-e607b9f`

resources/console/config.ts
=> feat: add me as developer

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-31a6990`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-6b1bfff`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-453d7a7`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-312e3f3`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-c706959`

Pulumi.prod.yaml
=> chore: bump workspace-agent tag to `main-2b8e85d`

Pulumi.prod.yaml
=> chore: bump workspace-agent-v2 tag to `fastify-refactor-5753993`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `main-03f3710`

Pulumi.prod.yaml
=> chore: bump calendar-agent tag to `fix-workflow-e45efef`

.github/workflows/refresh.yml, .github/workflows/update-app-tag.yml
I don't know who this cobraz character is supposed to be 🤷 
fixes #80 
Inspiration taken from https://github.com/getbranches/conf
=> fix: use simenandre github actions
